
///////////////////////////////////////////////////// AUTH TYPES ///////////////////////////////////

export const REGISTER_EMAIL_CHANGED = 'REGISTER_EMAIL_CHANGED';
export const REGISTER_PASSWORD_CHANGED = 'REGISTER_PASSWORD_CHANGED';
export const REGISTER_CONFIRM_PASSWORD_CHANGED = 'REGISTER_CONFIRM_PASSWORD_CHANGED';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_INVALID_EMAIL = 'REGISTER_INVALID_EMAIL';
export const REGISTER_INVALID_PASSWORD = 'REGISTER_INVALID_PASSWORD';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_EMAIL_CHANGED = 'LOGIN_EMAIL_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const LOGIN_USER = 'LOGIN_USER';
export const RECOVERY_EMAIL_CHANGED = 'RECOVERY_EMAIL_CHANGED';
export const RECOVER_ACCOUNT = 'RECOVER_ACCOUNT';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const PASSWORD_SENT_FAIL = 'PASSWORD_SENT_FAIL';
export const PASSWORD_SENT_SUCCESS = 'PASSWORD_SENT_SUCCESS';
export const DELETE_ACCOUNT_PASSWORD_CHANGED = 'DELETE_ACCOUNT_PASSWORD_CHANGED';
export const CHANGE_PASSWORD_OLD_CHANGED = 'CHANGE_PASSWORD_OLD_CHANGED';
export const CHANGE_PASSWORD_NEW_CHANGED = 'CHANGE_PASSWORD_NEW_CHANGED';
export const CHANGE_PASSWORD_NEW_CONFIRM_CHANGED = 'CHANGE_PASSWORD_NEW_CONFIRM_CHANGED';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const SHOW_CHANGE_PASSWORD = 'SHOW_CHANGE_PASSWORD';
export const HIDE_CHANGE_PASSWORD = 'HIDE_CHANGE_PASSWORD';

///////////////////////////////////////////////////// NOTE TYPES ///////////////////////////////////

export const NOTE_HEADING_CHANGED = 'NOTE_HEADING_CHANGED';
export const NOTE_CONTENT_CHANGED = 'NOTE_CONTENT_CHANGED';
export const NOTE_CREATE = 'NOTE_CREATE';
export const NOTES_FETCH_SUCCESS = 'NOTES_FETCH_SUCCESS';
export const NOTE_UPDATE = 'NOTE_UPDATE';
export const NOTE_SAVE_SUCCESS = 'NOTE_SAVE_SUCCESS';
